### ISSUE TITLE
Using the CLI to publish to a non-registered short topic name fails silently

### ISSUE THREAD

**Issue by simon622** [simon622/mqtt-sn#1]
Using the CLI to publish to a non-registered short topic name fails silently

**Comment by simon622** [comment]
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.charAt(String.java:658)
	at org.slj.mqtt.sn.impl.AbstractMqttsnMessageStateService.sendMessage(AbstractMqttsnMessageStateService.java:214)
	at org.slj.mqtt.sn.impl.MqttsnMessageQueueProcessor.dequeAndPublishNextMessage(MqttsnMessageQueueProcessor.java:127)
	at org.slj.mqtt.sn.impl.MqttsnMessageQueueProcessor.processNextMessage(MqttsnMessageQueueProcessor.java:117)
	at org.slj.mqtt.sn.impl.MqttsnMessageQueueProcessor.process(MqttsnMessageQueueProcessor.java:81)
	at org.slj.mqtt.sn.impl.AbstractMqttsnMessageStateService.processQueue(AbstractMqttsnMessageStateService.java:132)
	at org.slj.mqtt.sn.impl.AbstractMqttsnMessageStateService.lambda$scheduleWork$0(AbstractMqttsnMessageStateService.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by simon622** [comment]
fixed by v1.0.0-alpha3
