### ISSUE TITLE
Performance of PathTriesTree during high volume subscribe to same node in tree

### ISSUE THREAD

**Issue by simon622** [simon622/mqtt-sn#54]
java.lang.Thread.State: RUNNABLE
	at java.util.HashMap$HashIterator.nextNode(java.base@17.0.5/HashMap.java:1601)
	at java.util.HashMap$KeyIterator.next(java.base@17.0.5/HashMap.java:1620)
	at java.util.Collections$UnmodifiableCollection$1.next(java.base@17.0.5/Collections.java:1054)
	at java.util.AbstractCollection.addAll(java.base@17.0.5/AbstractCollection.java:335)
	at org.slj.mqtt.sn.utils.tree.PathTriesTree.searchTreeForMembers(PathTriesTree.java:234)
	at org.slj.mqtt.sn.utils.tree.PathTriesTree.searchMembers(PathTriesTree.java:157)
	at org.slj.mqtt.sn.utils.tree.PathTriesTree.hasMembers(PathTriesTree.java:161)

**Comment by simon622** [comment]
mqtt-sn-udp-transport-ingress-1229202732-1" #25 daemon prio=2 os_prio=31 cpu=34923.49ms elapsed=211.67s tid=0x000000014a030e00 nid=0x5707 runnable  [0x0000000291266000]
   java.lang.Thread.State: RUNNABLE
	at java.util.HashMap$HashIterator.nextNode(java.base@17.0.5/HashMap.java:1601)
	at java.util.HashMap$KeyIterator.next(java.base@17.0.5/HashMap.java:1620)
	at java.util.Collections$UnmodifiableCollection$1.next(java.base@17.0.5/Collections.java:1054)
	at java.util.AbstractCollection.addAll(java.base@17.0.5/AbstractCollection.java:335)
	at org.slj.mqtt.sn.utils.tree.PathTriesTree.searchTreeForMembers(PathTriesTree.java:234)
	at org.slj.mqtt.sn.utils.tree.PathTriesTree.searchMembers(PathTriesTree.java:157)
	at org.slj.mqtt.sn.utils.tree.PathTriesTree.hasMembers(PathTriesTree.java:161)
	at org.slj.mqtt.sn.impl.ram.MqttsnInMemorySubscriptionRegistry.hasSubscription(MqttsnInMemorySubscriptionRegistry.java:108)
	at org.slj.mqtt.sn.gateway.impl.gateway.type.MqttsnAggregatingGateway.subscribe(MqttsnAggregatingGateway.java:318)
	at org.slj.mqtt.sn.gateway.impl.gateway.MqttsnGatewaySessionService.subscribe(MqttsnGatewaySessionService.java:257)
	- locked <0x00000007fe873320> (a org.slj.mqtt.sn.model.ClientIdentifierContext)
	at org.slj.mqtt.sn.gateway.impl.gateway.MqttsnGatewayMessageHandler.handleSubscribe(MqttsnGatewayMessageHandler.java:321)
	at org.slj.mqtt.sn.impl.AbstractMqttsnMessageHandler.handle(AbstractMqttsnMessageHandler.java:218)
	at org.slj.mqtt.sn.impl.AbstractMqttsnMessageHandler.receiveMessage(AbstractMqttsnMessageHandler.java:129)
	at org.slj.mqtt.sn.impl.AbstractMqttsnTransport.receiveFromTransportInternal(AbstractMqttsnTransport.java:120)
	at org.slj.mqtt.sn.impl.AbstractTransport.lambda$receiveFromTransport$1(AbstractTransport.java:120)
	at org.slj.mqtt.sn.impl.AbstractTransport$$Lambda$187/0x0000000800d99668.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.5/Executors.java:539)
	at java.util.concurrent.FutureTask.run(java.base@17.0.5/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.5/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.5/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.5/Thread.java:833)

**Comment by simon622** [comment]
Fixed, abstracted to the MqttTree project which also includes performance work
