### ISSUE TITLE
Contention on network registry during concurrent additions and removals

### ISSUE THREAD

**Issue by simon622** [simon622/mqtt-sn#55]
"mqtt-sn-udp-transport-ingress-1771667101-1" #25 daemon prio=2 os_prio=31 cpu=8203.20ms elapsed=9.00s tid=0x000000013b811000 nid=0x5607 runnable  [0x000000016e252000]
   java.lang.Thread.State: RUNNABLE
	at java.util.HashMap$HashIterator.nextNode(java.base@17.0.5/HashMap.java:1601)
	at java.util.HashMap$KeyIterator.next(java.base@17.0.5/HashMap.java:1620)
	at org.slj.mqtt.sn.net.NetworkAddressRegistry.removeExistingClientId(NetworkAddressRegistry.java:137)
	- locked <0x00000007f8499dd8> (a java.util.Collections$SynchronizedMap)
	at org.slj.mqtt.sn.impl.AbstractMqttsnMessageHandler.authorizeContext(AbstractMqttsnMessageHandler.java:70)
	at org.slj.mqtt.sn.impl.AbstractMqttsnTransport.receiveFromTransportInternal(AbstractMqttsnTransport.java:80)
	at org.slj.mqtt.sn.impl.AbstractTransport.lambda$receiveFromTransport$1(AbstractTransport.java:120)
	at org.slj.mqtt.sn.impl.AbstractTransport$$Lambda$190/0x0000000800da5d08.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.5/Executors.java:539)
	at java.util.concurrent.FutureTask.run(java.base@17.0.5/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.5/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.5/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.5/Thread.java:833)

**Comment by simon622** [comment]
Changed data model to allow for higher concurrency
